services:
  
  thumbgen:
    build: .
    restart: unless-stopped
    # expose:  # note : this does not open port on host machine, it just exposes the port in docker compose's network. 
    #   - "4499"
    ports:  # Use this if you need to map host's port to container.
      - "4499:4499"  
